Phase - 06 ----> Feature Engineering

In [1]:
import pandas as pd
import numpy as np

print("Feature engineering notebook is working!")

Feature engineering notebook is working!

In [2]:
data_path = "../data/processed/movies_integrated.csv"
df = pd.read_csv(data_path)
print("Dataset shape:", df.shape)

Dataset shape: (569655, 9)

In [5]:
df.head()

,tconst,titleType,primaryTitle,startYear,runtimeMinutes,genres,genre_list,averageRating,numVotes
0,tt0000574,movie,The Story of the Kelly Gang,1906,70.0,"Action,Adventure,Biography","['Action', 'Adventure', 'Biography']",6.0,1084.0
1,tt0000591,movie,The Prodigal Son,1907,90.0,Drama,['Drama'],4.8,40.0
2,tt0000615,movie,Robbery Under Arms,1907,NaN,Drama,['Drama'],3.4,36.0
3,tt0000630,movie,Hamlet,1908,NaN,Drama,['Drama'],3.0,42.0
4,tt0000675,movie,Don Quijote,1908,NaN,Drama,['Drama'],3.8,32.0

In [6]:
print(df.columns.tolist())

['tconst', 'titleType', 'primaryTitle', 'startYear', 'runtimeMinutes', 'genres', 'genre_list', 'averageRating', 'numVotes']

In [7]:
#creating Year 
df["year"] = df["startYear"].astype(int)
print(df["year"].min())
print(df["year"].max())

1900
2026

In [8]:
#Creating Decade
df["decade"] = (df["year"] // 10) * 10
df[["primaryTitle", "year", "decade"]].head(10)

                     primaryTitle  year  decade
0     The Story of the Kelly Gang  1906    1900
1                The Prodigal Son  1907    1900
2              Robbery Under Arms  1907    1900
3                          Hamlet  1908    1900
4                     Don Quijote  1908    1900
5  The Fairylogue and Radio-Plays  1908    1900
6       Hamlet, Prince of Denmark  1910    1910
7                  Locura de amor  1909    1900
8                      Salome Mad  1909    1900
9                  Gøngehøvdingen  1909    1900

In [9]:
def assign_era(year):
    if year < 1930:
        return "Silent Era"
    elif year < 1960:
        return "Golden Age"
    elif year < 1980:
        return "New Hollywood Era"
    elif year < 2000:
        return "Modern Era"
    else:
        return "Digital Era"


df["era"] = df["year"].apply(assign_era)

df[["primaryTitle", "year", "decade", "era"]].head(20)

                         primaryTitle  year  decade         era
0         The Story of the Kelly Gang  1906    1900  Silent Era
1                    The Prodigal Son  1907    1900  Silent Era
2                  Robbery Under Arms  1907    1900  Silent Era
3                              Hamlet  1908    1900  Silent Era
4                         Don Quijote  1908    1900  Silent Era
5      The Fairylogue and Radio-Plays  1908    1900  Silent Era
6           Hamlet, Prince of Denmark  1910    1910  Silent Era
7                      Locura de amor  1909    1900  Silent Era
8                          Salome Mad  1909    1900  Silent Era
9                      Gøngehøvdingen  1909    1900  Silent Era
10           O Terremoto de Benavente  1909    1900  Silent Era
11                             Hamlet  1910    1910  Silent Era
12                      Ansigttyven I  1910    1910  Silent Era
13  O Centenário da Guerra Peninsular  1910    1910  Silent Era
14                   Corrida da Rampa  1910    1910  Silent Era
15                            Camille  1912    1910  Silent Era
16            Don Juan de Serrallonga  1910    1910  Silent Era
17                             Hamlet  1911    1910  Silent Era
18                        Kapergasten  1910    1910  Silent Era
19                  The Life of Moses  1909    1900  Silent Era

In [10]:
print("Movies by era:")
print(df["era"].value_counts())

Movies by era:
era
Digital Era          363860
Modern Era            75776
New Hollywood Era     59484
Golden Age            47646
Silent Era            22889
Name: count, dtype: int64

In [11]:
print("\nSample from each era:")

for era in df["era"].unique():
    print(f"\n--- {era} ---")
    print(
        df[df["era"] == era][
            ["primaryTitle", "year", "decade", "era"]
        ].head(3)
    )

Sample from each era:

--- Silent Era ---
                  primaryTitle  year  decade         era
0  The Story of the Kelly Gang  1906    1900  Silent Era
1             The Prodigal Son  1907    1900  Silent Era
2           Robbery Under Arms  1907    1900  Silent Era

--- Golden Age ---
            primaryTitle  year  decade         era
266     Dodge City Trail  1936    1930  Golden Age
7916  The Little Colonel  1935    1930  Golden Age
9339           Happiness  1935    1930  Golden Age

--- Digital Era ---
                                            primaryTitle  year  decade  \
4803                                    Tötet nicht mehr  2019    2010
21987                                     Kate & Leopold  2001    2000
42083  The Tango of the Widower and Its Distorting Mi...  2020    2020

               era
4803   Digital Era
21987  Digital Era
42083  Digital Era

--- Modern Era ---
                      primaryTitle  year  decade         era
7701                 Dama de noche  1993    1990  Modern Era
22866  Another Time, Another Place  1983    1980  Modern Era
23963    Shiva und die Galgenblume  1993    1990  Modern Era

--- New Hollywood Era ---
           primaryTitle  year  decade                era
22840  January 30, 1945  1965    1960  New Hollywood Era
25008     Habla, mudita  1973    1970  New Hollywood Era
25404    Viva Chihuahua  1961    1960  New Hollywood Era

In [12]:
CURRENT_YEAR = 2026
df["movie_age"] = CURRENT_YEAR - df["year"]
df[["primaryTitle", "year", "movie_age"]].head(10)

                     primaryTitle  year  movie_age
0     The Story of the Kelly Gang  1906        120
1                The Prodigal Son  1907        119
2              Robbery Under Arms  1907        119
3                          Hamlet  1908        118
4                     Don Quijote  1908        118
5  The Fairylogue and Radio-Plays  1908        118
6       Hamlet, Prince of Denmark  1910        116
7                  Locura de amor  1909        117
8                      Salome Mad  1909        117
9                  Gøngehøvdingen  1909        117

In [13]:
df["genre_count"] = df["genre_list"].apply(len)
df[
    ["primaryTitle", "genres", "genre_count"]
].head(20)

                         primaryTitle                      genres  genre_count
0         The Story of the Kelly Gang  Action,Adventure,Biography           36
1                    The Prodigal Son                       Drama            9
2                  Robbery Under Arms                       Drama            9
3                              Hamlet                       Drama            9
4                         Don Quijote                       Drama            9
5      The Fairylogue and Radio-Plays           Adventure,Fantasy           24
6           Hamlet, Prince of Denmark                       Drama            9
7                      Locura de amor                       Drama            9
8                          Salome Mad                      Comedy           10
9                      Gøngehøvdingen                   Drama,War           16
10           O Terremoto de Benavente                 Documentary           15
11                             Hamlet                       Drama            9
12                      Ansigttyven I                       Crime            9
13  O Centenário da Guerra Peninsular                 Documentary           15
14                   Corrida da Rampa                 Documentary           15
15                            Camille               Drama,Romance           20
16            Don Juan de Serrallonga             Adventure,Drama           22
17                             Hamlet                       Drama            9
18                        Kapergasten                       Drama            9
19                  The Life of Moses      Biography,Drama,Family           32

In [14]:
# Fix genre_list
df["genre_list"] = df["genres"].str.split(",")
# Recalculate genre count
df["genre_count"] = df["genre_list"].apply(len)
df[["primaryTitle", "genres", "genre_list", "genre_count"]].head(20)

,primaryTitle,genres,genre_list,genre_count
0,The Story of the Kelly Gang,"Action,Adventure,Biography","[Action, Adventure, Biography]",3
1,The Prodigal Son,Drama,[Drama],1
2,Robbery Under Arms,Drama,[Drama],1
3,Hamlet,Drama,[Drama],1
4,Don Quijote,Drama,[Drama],1
5,The Fairylogue and Radio-Plays,"Adventure,Fantasy","[Adventure, Fantasy]",2
6,"Hamlet, Prince of Denmark",Drama,[Drama],1
7,Locura de amor,Drama,[Drama],1
8,Salome Mad,Comedy,[Comedy],1
9,Gøngehøvdingen,"Drama,War","[Drama, War]",2
10,O Terremoto de Benavente,Documentary,[Documentary],1
11,Hamlet,Drama,[Drama],1
12,Ansigttyven I,Crime,[Crime],1
13,O Centenário da Guerra Peninsular,Documentary,[Documentary],1
14,Corrida da Rampa,Documentary,[Documentary],1
15,Camille,"Drama,Romance","[Drama, Romance]",2
16,Don Juan de Serrallonga,"Adventure,Drama","[Adventure, Drama]",2
17,Hamlet,Drama,[Drama],1
18,Kapergasten,Drama,[Drama],1
19,The Life of Moses,"Biography,Drama,Family","[Biography, Drama, Family]",3

In [15]:
print("Genre count distribution:")
print(df["genre_count"].value_counts().sort_index())

Genre count distribution:
genre_count
1    347224
2    124876
3     97555
Name: count, dtype: int64

In [16]:
print("Minimum genres per movie:", df["genre_count"].min())
print("Maximum genres per movie:", df["genre_count"].max())

Minimum genres per movie: 1
Maximum genres per movie: 3

In [17]:
# Get all unique genres
all_genres = sorted(df["genre_list"].explode().unique())

print("Total unique genres:", len(all_genres))
print("\nGenres:")
print(all_genres)

Total unique genres: 27

Genres:
['Action', 'Adult', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'Game-Show', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'News', 'Reality-TV', 'Romance', 'Sci-Fi', 'Sport', 'Talk-Show', 'Thriller', 'War', 'Western']

In [18]:
# Create binary indicator columns for each genre

for genre in all_genres:
    df[f"genre_{genre.lower().replace('-', '_').replace(' ', '_')}"] = (
        df["genre_list"].apply(lambda x: int(genre in x))
    )
print("Genre indicator columns created.")

Genre indicator columns created.

In [21]:
# Check actual genre indicator columns
indicator_columns = [
    f"genre_{genre.lower().replace('-', '_').replace(' ', '_')}"
    for genre in all_genres
]
print("Number of genre indicator columns:", len(indicator_columns))
print("\nGenre indicator columns:")
print(indicator_columns)

Number of genre indicator columns: 27

Genre indicator columns:
['genre_action', 'genre_adult', 'genre_adventure', 'genre_animation', 'genre_biography', 'genre_comedy', 'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family', 'genre_fantasy', 'genre_film_noir', 'genre_game_show', 'genre_history', 'genre_horror', 'genre_music', 'genre_musical', 'genre_mystery', 'genre_news', 'genre_reality_tv', 'genre_romance', 'genre_sci_fi', 'genre_sport', 'genre_talk_show', 'genre_thriller', 'genre_war', 'genre_western']

In [22]:
df[
    [
        "primaryTitle",
        "genres",
        "genre_count",
        "genre_action",
        "genre_adventure",
        "genre_drama",
        "genre_comedy"
    ]
].head(20)

,primaryTitle,genres,genre_count,genre_action,genre_adventure,genre_drama,genre_comedy
0,The Story of the Kelly Gang,"Action,Adventure,Biography",3,1,1,0,0
1,The Prodigal Son,Drama,1,0,0,1,0
2,Robbery Under Arms,Drama,1,0,0,1,0
3,Hamlet,Drama,1,0,0,1,0
4,Don Quijote,Drama,1,0,0,1,0
5,The Fairylogue and Radio-Plays,"Adventure,Fantasy",2,0,1,0,0
6,"Hamlet, Prince of Denmark",Drama,1,0,0,1,0
7,Locura de amor,Drama,1,0,0,1,0
8,Salome Mad,Comedy,1,0,0,0,1
9,Gøngehøvdingen,"Drama,War",2,0,0,1,0
10,O Terremoto de Benavente,Documentary,1,0,0,0,0
11,Hamlet,Drama,1,0,0,1,0
12,Ansigttyven I,Crime,1,0,0,0,0
13,O Centenário da Guerra Peninsular,Documentary,1,0,0,0,0
14,Corrida da Rampa,Documentary,1,0,0,0,0
15,Camille,"Drama,Romance",2,0,0,1,0
16,Don Juan de Serrallonga,"Adventure,Drama",2,0,1,1,0
17,Hamlet,Drama,1,0,0,1,0
18,Kapergasten,Drama,1,0,0,1,0
19,The Life of Moses,"Biography,Drama,Family",3,0,0,1,0

In [23]:
# Create decade feature
df["decade"] = (df["year"] // 10) * 10
print("Decade feature created.")
print(df[["primaryTitle", "year", "decade"]].head(10))

Decade feature created.
                     primaryTitle  year  decade
0     The Story of the Kelly Gang  1906    1900
1                The Prodigal Son  1907    1900
2              Robbery Under Arms  1907    1900
3                          Hamlet  1908    1900
4                     Don Quijote  1908    1900
5  The Fairylogue and Radio-Plays  1908    1900
6       Hamlet, Prince of Denmark  1910    1910
7                  Locura de amor  1909    1900
8                      Salome Mad  1909    1900
9                  Gøngehøvdingen  1909    1900

In [24]:
print(df[["primaryTitle", "year", "movie_age"]].head(10))

                     primaryTitle  year  movie_age
0     The Story of the Kelly Gang  1906        120
1                The Prodigal Son  1907        119
2              Robbery Under Arms  1907        119
3                          Hamlet  1908        118
4                     Don Quijote  1908        118
5  The Fairylogue and Radio-Plays  1908        118
6       Hamlet, Prince of Denmark  1910        116
7                  Locura de amor  1909        117
8                      Salome Mad  1909        117
9                  Gøngehøvdingen  1909        117

In [25]:
# Create runtime categories
def classify_runtime(runtime):
    if pd.isna(runtime):
        return "Unknown"
    elif runtime < 90:
        return "Short"
    elif runtime <= 150:
        return "Medium"
    else:
        return "Long"

df["runtime_category"] = df["runtimeMinutes"].apply(classify_runtime)

print(df[["primaryTitle", "runtimeMinutes", "runtime_category"]].head(20))

                         primaryTitle  runtimeMinutes runtime_category
0         The Story of the Kelly Gang            70.0            Short
1                    The Prodigal Son            90.0           Medium
2                  Robbery Under Arms             NaN          Unknown
3                              Hamlet             NaN          Unknown
4                         Don Quijote             NaN          Unknown
5      The Fairylogue and Radio-Plays           120.0           Medium
6           Hamlet, Prince of Denmark             NaN          Unknown
7                      Locura de amor            45.0            Short
8                          Salome Mad             NaN          Unknown
9                      Gøngehøvdingen             NaN          Unknown
10           O Terremoto de Benavente             NaN          Unknown
11                             Hamlet             NaN          Unknown
12                      Ansigttyven I             NaN          Unknown
13  O Centenário da Guerra Peninsular             NaN          Unknown
14                   Corrida da Rampa             NaN          Unknown
15                            Camille             NaN          Unknown
16            Don Juan de Serrallonga            58.0            Short
17                             Hamlet             NaN          Unknown
18                        Kapergasten             NaN          Unknown
19                  The Life of Moses            50.0            Short

In [26]:
print("Runtime category distribution:")
print(df["runtime_category"].value_counts())

Runtime category distribution:
runtime_category
Short      222024
Medium     209327
Unknown    128235
Long        10069
Name: count, dtype: int64

In [27]:
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (569655, 42)

Columns:
['tconst', 'titleType', 'primaryTitle', 'startYear', 'runtimeMinutes', 'genres', 'genre_list', 'averageRating', 'numVotes', 'year', 'decade', 'era', 'movie_age', 'genre_count', 'genre_action', 'genre_adult', 'genre_adventure', 'genre_animation', 'genre_biography', 'genre_comedy', 'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family', 'genre_fantasy', 'genre_film_noir', 'genre_game_show', 'genre_history', 'genre_horror', 'genre_music', 'genre_musical', 'genre_mystery', 'genre_news', 'genre_reality_tv', 'genre_romance', 'genre_sci_fi', 'genre_sport', 'genre_talk_show', 'genre_thriller', 'genre_war', 'genre_western', 'runtime_category']

In [28]:
print("Total columns:", len(df.columns))

for i, col in enumerate(df.columns, start=1):
    print(i, col)

Total columns: 42
1 tconst
2 titleType
3 primaryTitle
4 startYear
5 runtimeMinutes
6 genres
7 genre_list
8 averageRating
9 numVotes
10 year
11 decade
12 era
13 movie_age
14 genre_count
15 genre_action
16 genre_adult
17 genre_adventure
18 genre_animation
19 genre_biography
20 genre_comedy
21 genre_crime
22 genre_documentary
23 genre_drama
24 genre_family
25 genre_fantasy
26 genre_film_noir
27 genre_game_show
28 genre_history
29 genre_horror
30 genre_music
31 genre_musical
32 genre_mystery
33 genre_news
34 genre_reality_tv
35 genre_romance
36 genre_sci_fi
37 genre_sport
38 genre_talk_show
39 genre_thriller
40 genre_war
41 genre_western
42 runtime_category

In [29]:
print("===== FEATURE ENGINEERING CHECK =====")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(df.isna().sum())

print("\nRuntime categories:")
print(df["runtime_category"].value_counts())

print("\nGenre count:")
print(df["genre_count"].value_counts().sort_index())

===== FEATURE ENGINEERING CHECK =====
Rows: 569655
Columns: 42

Missing values:
tconst                    0
titleType                 0
primaryTitle              0
startYear                 0
runtimeMinutes       128235
genres                    0
genre_list                0
averageRating        231990
numVotes             231990
year                      0
decade                    0
era                       0
movie_age                 0
genre_count               0
genre_action              0
genre_adult               0
genre_adventure           0
genre_animation           0
genre_biography           0
genre_comedy              0
genre_crime               0
genre_documentary         0
genre_drama               0
genre_family              0
genre_fantasy             0
genre_film_noir           0
genre_game_show           0
genre_history             0
genre_horror              0
genre_music               0
genre_musical             0
genre_mystery             0
genre_news                0
genre_reality_tv          0
genre_romance             0
genre_sci_fi              0
genre_sport               0
genre_talk_show           0
genre_thriller            0
genre_war                 0
genre_western             0
runtime_category          0
dtype: int64

Runtime categories:
runtime_category
Short      222024
Medium     209327
Unknown    128235
Long        10069
Name: count, dtype: int64

Genre count:
genre_count
1    347224
2    124876
3     97555
Name: count, dtype: int64

In [30]:
# Create rating categories
def classify_rating(rating):
    if pd.isna(rating):
        return "Unrated"
    elif rating < 5:
        return "Low"
    elif rating < 7:
        return "Average"
    elif rating < 8:
        return "Good"
    else:
        return "Excellent"

df["rating_category"] = df["averageRating"].apply(classify_rating)
print(df[["primaryTitle", "averageRating", "rating_category"]].head(20))

                         primaryTitle  averageRating rating_category
0         The Story of the Kelly Gang            6.0         Average
1                    The Prodigal Son            4.8             Low
2                  Robbery Under Arms            3.4             Low
3                              Hamlet            3.0             Low
4                         Don Quijote            3.8             Low
5      The Fairylogue and Radio-Plays            4.9             Low
6           Hamlet, Prince of Denmark            4.0             Low
7                      Locura de amor            4.2             Low
8                          Salome Mad            3.6             Low
9                      Gøngehøvdingen            3.8             Low
10           O Terremoto de Benavente            2.6             Low
11                             Hamlet            3.8             Low
12                      Ansigttyven I            3.8             Low
13  O Centenário da Guerra Peninsular            NaN         Unrated
14                   Corrida da Rampa            NaN         Unrated
15                            Camille            5.5         Average
16            Don Juan de Serrallonga            3.2             Low
17                             Hamlet            3.8             Low
18                        Kapergasten            3.9             Low
19                  The Life of Moses            5.2         Average

In [31]:
print("Rating category distribution:")
print(df["rating_category"].value_counts())

Rating category distribution:
rating_category
Unrated      231990
Average      180181
Good          67351
Low           62393
Excellent     27740
Name: count, dtype: int64

In [32]:
import numpy as np
# Log-transformed vote count
df["log_votes"] = np.log1p(df["numVotes"])

print(df[["primaryTitle", "numVotes", "log_votes"]].head(20))

                         primaryTitle  numVotes  log_votes
0         The Story of the Kelly Gang    1084.0   6.989335
1                    The Prodigal Son      40.0   3.713572
2                  Robbery Under Arms      36.0   3.610918
3                              Hamlet      42.0   3.761200
4                         Don Quijote      32.0   3.496508
5      The Fairylogue and Radio-Plays      82.0   4.418841
6           Hamlet, Prince of Denmark      49.0   3.912023
7                      Locura de amor      39.0   3.688879
8                          Salome Mad      31.0   3.465736
9                      Gøngehøvdingen      27.0   3.332205
10           O Terremoto de Benavente       7.0   2.079442
11                             Hamlet      67.0   4.219508
12                      Ansigttyven I      30.0   3.433987
13  O Centenário da Guerra Peninsular       NaN        NaN
14                   Corrida da Rampa       NaN        NaN
15                            Camille      54.0   4.007333
16            Don Juan de Serrallonga      28.0   3.367296
17                             Hamlet      27.0   3.332205
18                        Kapergasten      32.0   3.496508
19                  The Life of Moses      90.0   4.510860

In [33]:
# Create popularity categories based on number of votes
def classify_popularity(votes):
    if pd.isna(votes):
        return "Unknown"
    elif votes < 100:
        return "Low"
    elif votes < 1000:
        return "Moderate"
    elif votes < 10000:
        return "Popular"
    else:
        return "Highly Popular"

df["popularity_category"] = df["numVotes"].apply(classify_popularity)
print(
    df[
        ["primaryTitle", "numVotes", "popularity_category"]
    ].head(20)
)

                         primaryTitle  numVotes popularity_category
0         The Story of the Kelly Gang    1084.0             Popular
1                    The Prodigal Son      40.0                 Low
2                  Robbery Under Arms      36.0                 Low
3                              Hamlet      42.0                 Low
4                         Don Quijote      32.0                 Low
5      The Fairylogue and Radio-Plays      82.0                 Low
6           Hamlet, Prince of Denmark      49.0                 Low
7                      Locura de amor      39.0                 Low
8                          Salome Mad      31.0                 Low
9                      Gøngehøvdingen      27.0                 Low
10           O Terremoto de Benavente       7.0                 Low
11                             Hamlet      67.0                 Low
12                      Ansigttyven I      30.0                 Low
13  O Centenário da Guerra Peninsular       NaN             Unknown
14                   Corrida da Rampa       NaN             Unknown
15                            Camille      54.0                 Low
16            Don Juan de Serrallonga      28.0                 Low
17                             Hamlet      27.0                 Low
18                        Kapergasten      32.0                 Low
19                  The Life of Moses      90.0                 Low

In [34]:
print("Popularity distribution:")
print(df["popularity_category"].value_counts())

Popularity distribution:
popularity_category
Unknown           231990
Low               191680
Moderate           97141
Popular            36310
Highly Popular     12534
Name: count, dtype: int64

In [35]:
# Rating weighted by log of votes
df["rating_popularity_score"] = (
    df["averageRating"] * df["log_votes"]
)
print(
    df[
        [
            "primaryTitle",
            "averageRating",
            "numVotes",
            "rating_popularity_score"
        ]
    ].head(20)
)

                         primaryTitle  averageRating  numVotes  \
0         The Story of the Kelly Gang            6.0    1084.0
1                    The Prodigal Son            4.8      40.0
2                  Robbery Under Arms            3.4      36.0
3                              Hamlet            3.0      42.0
4                         Don Quijote            3.8      32.0
5      The Fairylogue and Radio-Plays            4.9      82.0
6           Hamlet, Prince of Denmark            4.0      49.0
7                      Locura de amor            4.2      39.0
8                          Salome Mad            3.6      31.0
9                      Gøngehøvdingen            3.8      27.0
10           O Terremoto de Benavente            2.6       7.0
11                             Hamlet            3.8      67.0
12                      Ansigttyven I            3.8      30.0
13  O Centenário da Guerra Peninsular            NaN       NaN
14                   Corrida da Rampa            NaN       NaN
15                            Camille            5.5      54.0
16            Don Juan de Serrallonga            3.2      28.0
17                             Hamlet            3.8      27.0
18                        Kapergasten            3.9      32.0
19                  The Life of Moses            5.2      90.0

    rating_popularity_score
0                 41.936012
1                 17.825146
2                 12.277121
3                 11.283600
4                 13.286729
5                 21.652319
6                 15.648092
7                 15.493294
8                 12.476649
9                 12.662377
10                 5.406548
11                16.034129
12                13.049151
13                      NaN
14                      NaN
15                22.040333
16                10.775347
17                12.662377
18                13.636379
19                23.456469

In [36]:
new_features = [
    "decade",
    "era",
    "movie_age",
    "genre_count",
    "runtime_category",
    "rating_category",
    "log_votes",
    "popularity_category",
    "rating_popularity_score"
]

print("New engineered features:")
print(new_features)

print("\nFeature data:")
print(df[new_features].head(10))

New engineered features:
['decade', 'era', 'movie_age', 'genre_count', 'runtime_category', 'rating_category', 'log_votes', 'popularity_category', 'rating_popularity_score']

Feature data:
   decade         era  movie_age  genre_count runtime_category  \
0    1900  Silent Era        120            3            Short
1    1900  Silent Era        119            1           Medium
2    1900  Silent Era        119            1          Unknown
3    1900  Silent Era        118            1          Unknown
4    1900  Silent Era        118            1          Unknown
5    1900  Silent Era        118            2           Medium
6    1910  Silent Era        116            1          Unknown
7    1900  Silent Era        117            1            Short
8    1900  Silent Era        117            1          Unknown
9    1900  Silent Era        117            2          Unknown

  rating_category  log_votes popularity_category  rating_popularity_score
0         Average   6.989335             Popular                41.936012
1             Low   3.713572                 Low                17.825146
2             Low   3.610918                 Low                12.277121
3             Low   3.761200                 Low                11.283600
4             Low   3.496508                 Low                13.286729
5             Low   4.418841                 Low                21.652319
6             Low   3.912023                 Low                15.648092
7             Low   3.688879                 Low                15.493294
8             Low   3.465736                 Low                12.476649
9             Low   3.332205                 Low                12.662377

In [37]:
print("========== FINAL FEATURE ENGINEERING CHECK ==========")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nNew feature missing values:")
print(df[new_features].isna().sum())

print("\nRating categories:")
print(df["rating_category"].value_counts())

print("\nPopularity categories:")
print(df["popularity_category"].value_counts())

print("\nRuntime categories:")
print(df["runtime_category"].value_counts())

========== FINAL FEATURE ENGINEERING CHECK ==========
Rows: 569655
Columns: 46

New feature missing values:
decade                          0
era                             0
movie_age                       0
genre_count                     0
runtime_category                0
rating_category                 0
log_votes                  231990
popularity_category             0
rating_popularity_score    231990
dtype: int64

Rating categories:
rating_category
Unrated      231990
Average      180181
Good          67351
Low           62393
Excellent     27740
Name: count, dtype: int64

Popularity categories:
popularity_category
Unknown           231990
Low               191680
Moderate           97141
Popular            36310
Highly Popular     12534
Name: count, dtype: int64

Runtime categories:
runtime_category
Short      222024
Medium     209327
Unknown    128235
Long        10069
Name: count, dtype: int64

In [38]:
# Save feature-engineered dataset
output_path = "../data/processed/movies_feature_engineered.csv"
df.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: ../data/processed/movies_feature_engineered.csv

In [39]:
import os
print("File exists:", os.path.exists(output_path))
if os.path.exists(output_path):
    size_mb = os.path.getsize(output_path) / (1024 * 1024)
    print("File size:", round(size_mb, 2), "MB")

File exists: True
File size: 112.88 MB